[package]
name = "gb-core"
version = "0.1.8"
edition = "2024"
rust-version = "1.93"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5"

[dev-dependencies]
criterion = "0.5.1"
serde_json = "1.0"

[[bench]]
name = "cpu_phase6"
harness = false

[[bench]]
name = "ppu_phase6"
harness = false
