[alias]
fmt-check = "fmt --all --check"
lint = "clippy --workspace --all-targets -- -D warnings"
tests = "test --workspace"
cov = "llvm-cov --workspace --summary-only"
cov-check = "llvm-cov -p gb-core -p gb-test-runner -p gb-persistence --summary-only --fail-under-lines 90 --fail-under-regions 90 --fail-under-functions 90"
cov-html = "llvm-cov --workspace --html"
cov-lcov = "llvm-cov --workspace --lcov --output-path lcov.info"
deny-check = "deny check"
