[alias]
fmt-check = "fmt --all --check"
lint = "clippy --workspace --all-targets -- -D warnings"
tests = "test --workspace"
cov-clean = "llvm-cov clean --workspace"
cov-run = "llvm-cov --workspace --no-report"
cov-check-core = "llvm-cov report -p gb-core --summary-only --fail-under-lines 90 --fail-under-regions 90 --fail-under-functions 90"
cov-check-test-runner = "llvm-cov report -p gb-test-runner --summary-only --fail-under-lines 84.22 --fail-under-regions 84.63 --fail-under-functions 78.87"
cov-check-persistence = "llvm-cov report -p gb-persistence --summary-only --fail-under-lines 84.84 --fail-under-regions 79.37 --fail-under-functions 84.44"
cov-check-cli = "llvm-cov report -p gb-cli --summary-only --fail-under-lines 64.47 --fail-under-regions 61.23 --fail-under-functions 59.48"
cov-check-desktop = "llvm-cov report -p gb-desktop --summary-only --fail-under-lines 45.24 --fail-under-regions 48.05 --fail-under-functions 48.76"
cov-html = "llvm-cov --workspace --html"
deny-check = "deny check"
