[alias]
rom-bench = "run --release -q -p gb-benchmark --bin bench --"
rom-fetch = "run --release -q -p gb-test-runner --bin fetch --"
rom-suite = "run --release -q -p gb-test-runner --bin suite --"
rom-suite-link = "run --release -q -p gb-test-runner --bin suite_link --"
run-desktop = "run --release -p gb-desktop --"
fmt-check = "fmt --all --check"
lint = "clippy --workspace --all-targets -- -D warnings"
tests = "test --workspace"
cov-clean = "llvm-cov clean --workspace"
cov-run = "llvm-cov --workspace --no-report"
cov-check-core = "llvm-cov report -p gb-core --summary-only --fail-under-lines 96.00 --fail-under-regions 95.95 --fail-under-functions 98.29"
cov-check-test-runner = "llvm-cov report -p gb-test-runner --summary-only --fail-under-lines 85 --fail-under-regions 85 --fail-under-functions 80"
cov-check-persistence = "llvm-cov report -p gb-persistence --summary-only --fail-under-lines 96.66 --fail-under-regions 91.93 --fail-under-functions 94.68"
cov-check-cli = "llvm-cov report -p gb-cli --summary-only --fail-under-lines 92.52 --fail-under-regions 90.01 --fail-under-functions 92.30"
cov-check-desktop = "llvm-cov report -p gb-desktop --summary-only --fail-under-lines 93.80 --fail-under-regions 93.20 --fail-under-functions 94.70"
cov-html = "llvm-cov --workspace --html"
deny-check = "deny check"
