name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      LINUX_DESKTOP_FEATURES: gb-desktop/sdl3-build-from-source

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy, llvm-tools

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny

      - name: Install typos-cli
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli

      - name: Format
        run: cargo fmt-check

      - name: Lint
        run: cargo clippy --workspace --all-targets --features "${LINUX_DESKTOP_FEATURES}" -- -D warnings

      - name: Tests
        run: cargo test --workspace --features "${LINUX_DESKTOP_FEATURES}"

      - name: Typos
        run: typos

      - name: Deny
        run: cargo deny-check

      - name: Coverage
        run: cargo cov-check
