name: test-roms

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  acid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run Acid ROM suite
        run: make run-acid

  blargg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run Blargg ROM suite
        run: make run-blargg

  hacktix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run Hacktix ROM suite
        run: make run-hacktix

  cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run CPP ROM suite
        run: make run-cpp

  mooneye:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run Mooneye ROM suite
        run: make run-mooneye
