name: test-roms-gbmicrotest

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  test-roms-gbmicrotest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run gbmicrotest ROM suite
        run: cargo rom-suite gbmicrotest
