name: test-roms

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-roms:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Acid
            command: make run-acid
          - name: Blargg
            command: make run-blargg
          - name: Daid
            command: make run-daid
          - name: Hacktix
            command: make run-hacktix
          - name: CPP
            command: make run-cpp
          - name: Mooneye
            command: make run-mooneye
          - name: Mealybug
            command: make run-mealybug

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run ${{ matrix.name }} ROM suite
        run: ${{ matrix.command }}
